CREATE TABLE movies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tmdb_id BIGINT NOT NULL UNIQUE, -- ID oficial do filme no TMDB
    title VARCHAR(255) NOT NULL,
    original_title VARCHAR(255),
    overview TEXT, -- Sinopse (usamos TEXT porque é longa)
    poster_path VARCHAR(255), -- Caminho da imagem do poster (ex: /h595...jpg)
    backdrop_path VARCHAR(255), -- Caminho da imagem de fundo
    release_date VARCHAR(20),
    vote_average DOUBLE PRECISION, -- Nota média no TMDB
    popularity DOUBLE PRECISION
);