CREATE TABLE user_movies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    movie_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    user_rating INTEGER,
    user_review TEXT,
    added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_user_movie UNIQUE (user_id, movie_id),

    CONSTRAINT fk_user_movies_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_movies_movie FOREIGN KEY (movie_id) REFERENCES movies(id) ON DELETE CASCADE
);