CREATE TABLE user_movies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    movie_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL, -- WATCHLIST, WATCHED, DROPPED
    user_rating INTEGER, -- Nota pessoal do usuário (ex: 1 a 10)
    user_review TEXT, -- Comentário do usuário sobre o filme
    added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- Garante que o usuário não adicione o mesmo filme duas vezes na lista dele
    CONSTRAINT uk_user_movie UNIQUE (user_id, movie_id),

    -- Chaves estrangeiras com DELETE CASCADE (se apagar o usuário, apaga a lista dele)
    CONSTRAINT fk_user_movies_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_movies_movie FOREIGN KEY (movie_id) REFERENCES movies(id) ON DELETE CASCADE
);